from pathlib import Path
from typing import Final, Set, Tuple

import discord
from Crypto.Random import random as rand
from discord.ext import commands

from database.stats.StatsDatabase import collectCommandStats
from modules.TZBot import TZBot
from shared.Helpers import Helpers
from shell.Logger import Logger


class ImageGen(commands.Cog):
    COLORLIST_FILE: Final[Path] = Path("state/colorlist.bin")
    colorSet: Set[Tuple[int, int, int]]

    def __init__(this, client: TZBot) -> None:
        this.client = client

        if not Helpers.BMPGEN_EXEC_FILE.is_file():
            Logger.warning(f"BMPGen executable not found at {Helpers.BMPGEN_EXEC_FILE}")
        if not Helpers.MAGICK_EXEC_FILE.is_file():
            Logger.warning(f"ImageMagick executable not found at {Helpers.MAGICK_EXEC_FILE}")

        if not this.COLORLIST_FILE.is_file():
            this.colorSet = set()
            this.COLORLIST_FILE.touch(exist_ok=True)
        else:
            with this.COLORLIST_FILE.open("rb") as f:
                data = f.read()
                this.colorSet = {(data[i], data[i + 1], data[i + 2]) for i in range(0, len(data), 3)}

    @discord.slash_command(name="generate", description="Generate an image using math!")
    @commands.cooldown(1, 10, commands.BucketType.user)
    @collectCommandStats
    async def generate(
        this,
        ctx: discord.ApplicationContext,
        r: discord.Option(str, "Math expression for red") = "0",
        g: discord.Option(str, "Math expression for green") = "0",
        b: discord.Option(str, "Math expression for blue") = "0",
    ) -> bool:
        resp = await Helpers.generateImage(r, g, b)
        if not resp[0]:
            embed = await this.client.getFail(description="An error occured. Please try again.", user=ctx.user)
            await ctx.response.send_message(embed=embed, ephemeral=True)
            ctx.command.reset_cooldown(ctx)
            return False

        file = discord.File(resp[1], filename="pattern.png")
        await ctx.response.send_message("Here's your picture!", file=file)
        return True

    @discord.slash_command(name="color", description="Generate a random unique (or not unique) color! Uses crypto random")
    @commands.cooldown(1, 3, commands.BucketType.user)
    @collectCommandStats
    async def color(this, ctx: discord.ApplicationContext) -> bool:
        if not (Helpers.BMPGEN_EXEC_FILE.is_file() and Helpers.MAGICK_EXEC_FILE.is_file()):
            await ctx.respond("This feature is disabled.")

        color: tuple[int, int, int] = (rand.randint(0, 255), rand.randint(0, 255), rand.randint(0, 255))
        fileOutput = color[0].to_bytes(1, byteorder="little") + color[1].to_bytes(1, byteorder="little") + color[2].to_bytes(1, byteorder="little")

        resp = await Helpers.generateImage(str(color[0]), str(color[1]), str(color[2]))
        if not resp[0]:
            embed = await this.client.getFail(description="An error occured. Please try again.", user=ctx.user)
            await ctx.response.send_message(embed=embed, ephemeral=True)
            ctx.command.reset_cooldown(ctx)
            return False

        file = discord.File(resp[1], filename="color.png")
        if color not in this.colorSet:
            await ctx.response.send_message(
                " ".join([f"**#{format(color[0], '02x')}{format(color[1], '02x')}{format(color[2], '02x')}** is", "your random unique color!"]),
                file=file,
            )

            this.colorSet.add(color)
            with this.COLORLIST_FILE.open("ab") as writer:
                writer.write(fileOutput)

        else:
            await ctx.response.send_message( " ".join([
                        f"**#{format(color[0], '02x')}{format(color[1], '02x')}{format(color[2], '02x')}**",
                        f"was already generated by someone. Duplicate after **{len(this.colorSet)}** total tries. That's",
                        f"~**{str((len(this.colorSet) * 100) / (256**3)).replace('.', ',')} %** chance! How unlucky! (or lucky?)",
                    ]), file=file)

        return True


def setup(client: TZBot) -> None:
    client.add_cog(ImageGen(client))
